### ISSUE TITLE
Extra console log?

### ISSUE THREAD

**Issue by AustinGil** [loicgeek/vue-easy-printer#1]
https://github.com/loicgeek/vue-easy-printer/blob/f21a7810214a220bb7b1ca7879d25544c092c57f/src/PrinterModelComponent.vue#L17

I noticed there is a console.log in the mounted hook. Any reason that should be in there?

**Comment by loic11111** [comment]
@Stegosource no, there is no reason,  it was just for debugging purpose.there are a lot of code to clean, it will be done on the next release

**Comment by AustinGil** [comment]
Ah ok. Sounds good.
